# Generated by Django 4.2.5 on 2023-09-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IdCliente', models.AutoField(primary_key=True, serialize=False)),
                ('NomeCliente', models.CharField(max_length=100)),
                ('EmailCliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('TelCliente', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
