# Generated by Django 4.2.5 on 2023-09-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadcli', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='EmailCliente',
            new_name='email_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='IdCliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='NomeCliente',
            new_name='nome_cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='TelCliente',
            new_name='tel_cliente',
        ),
    ]
