# Generated by Django 4.2.5 on 2023-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadcli', '0002_rename_emailcliente_cliente_email_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email_cliente',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel_cliente',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
