# Generated by Django 4.2.5 on 2023-11-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadcli', '0003_alter_cliente_email_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id_cliente']},
        ),
    ]
